apiVersion: build.tanzu.vmware.com/v1
kind: ContainerAppBuildPlan
metadata:
  name: platform-config
spec:
  registry: ""
  nonSecretEnv:
  - name: BP_JVM_VERSION
    value: "21"
  buildpacks:
    builder: "paketobuildpacks/builder-jammy-base"

  runtimes:
  - name: kubernetes-carvel-package
    description: Deployment-based Kubernetes configuration
    steps:
    - namedTask: tanzu-kubernetes-deployment
    - namedTask: tanzu-carvel-package
